stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  script:
    - git checkout master
    - git pull origin master
    - git push -f git@github.com:namboy94/raspi-8-bit-counter.git master

checkstyle:
  stage: test
  script:
    - pep8 .
